### ISSUE TITLE
CalculateShortestRoute

### ISSUE THREAD

**Issue by zeeshanjan82** [GuyHarwood/TravellingSalesman#1]
I liked the implementation, however did not quire understood the CalculateShortestRoute method, currently it throws NotImplementedException, as I understand you are passing the first destination as an input param and then inside the function you are creating a new Queue for route and then you are planning to loop through each route in that queue and calculate the distance from the input route to each one. Can you share more thoughts on this?

**Comment by GuyHarwood** [comment]
This was never finished.  Feel free to send me a PR if you decide to fork it and implement yourself :)
